-- Script para crear tablas de la base de datos de urbango sin contar tablas del traccar las tablas de traccar deben de generarse por sepraado al levantar el servidor del traccar  
-- Se dejo iddevice sni fk para agregarla despues que se agrege el primer rastreador esto para no tener problemas con los rastreadores en el traccar simplemente los vincularemos despues

-- PostGIS (necesario para columnas geometry)
CREATE EXTENSION IF NOT EXISTS postgis;

-- Esquemas
CREATE SCHEMA IF NOT EXISTS urb;
CREATE SCHEMA IF NOT EXISTS urb_sistema;

-- =========================================================
-- 1) urb.pais
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.organizacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS urb.pais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

-- =========================================================
-- 2) urb.estado_localidad
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.estado_localidad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  id_pais BIGINT NOT NULL,
  CONSTRAINT fk_estado_localidad_pais
    FOREIGN KEY (id_pais) REFERENCES urb.pais(id)
);

-- =========================================================
-- 3) urb.municipio
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.municipio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  id_estado_localidad BIGINT NOT NULL,
  CONSTRAINT fk_municipio_estado_localidad
    FOREIGN KEY (id_estado_localidad) REFERENCES urb.estado_localidad(id)
);

-- =========================================================
-- 4) urb.codigo_postal
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.codigo_postal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cp VARCHAR(20) NOT NULL,
  id_municipio BIGINT NOT NULL,
  CONSTRAINT fk_codigo_postal_municipio
    FOREIGN KEY (id_municipio) REFERENCES urb.municipio(id)
);

-- =========================================================
-- 5) urb.tipo_asentamiento
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.tipo_asentamiento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

-- =========================================================
-- 6) urb.asentamiento
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.asentamiento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  id_tipo_asentamiento BIGINT NOT NULL,
  id_cp BIGINT NOT NULL,
  CONSTRAINT fk_asentamiento_tipo_asentamiento
    FOREIGN KEY (id_tipo_asentamiento) REFERENCES urb.tipo_asentamiento(id),
  CONSTRAINT fk_asentamiento_codigo_postal
    FOREIGN KEY (id_cp) REFERENCES urb.codigo_postal(id)
);

-- =========================================================
-- (Tabla de soporte) urb.direccion
-- Nota: viene implícita por id_direccion en POI
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.direccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calle VARCHAR(100) NOT NULL,
  numero_exterior VARCHAR(20) NOT NULL,
  id_asentamiento BIGINT NOT NULL,
  CONSTRAINT fk_direccion_asentamiento
    FOREIGN KEY (id_asentamiento) REFERENCES urb.asentamiento(id)
);

-- =========================================================
-- 7) urb.tipo_camion
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.tipo_camion (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

-- =========================================================
-- 8) urb.poi
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.poi (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  categoria TEXT NOT NULL,
  id_direccion BIGINT NOT NULL,
  rating NUMERIC(3,2) NULL,
  geom geometry(Point, 4326) NOT NULL,
  fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  horario TEXT,
  CONSTRAINT fk_poi_direccion
    FOREIGN KEY (id_direccion) REFERENCES urb.direccion(id)
);

-- =========================================================
-- 13) urb.estado
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.estado (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);
-- =========================================================
-- 9) urb.ruta sqlWITH ruta_id AS (  SELECT p.idruta AS id_vieja ,u.id AS id_ruta  FROM public.urb_ruta p INNER JOIN urb.ruta u  ON u.nombre = p.nombre )  ;
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.ruta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  id_ciudad BIGINT NOT NULL,
  id_tipo_camion INT NOT NULL,
  id_estado INT NOT NULL,
  id_organizacion BIGINT NOT NULL,
  CONSTRAINT fk_ruta_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id),
  CONSTRAINT fk_ruta_tipo_camion
    FOREIGN KEY (id_tipo_camion) REFERENCES urb.tipo_camion(id),
  CONSTRAINT fk_ruta_organizacion
    FOREIGN KEY (id_organizacion) REFERENCES urb.organizacion(id),
  CONSTRAINT fk_ruta_ciudad
    FOREIGN KEY (id_ciudad) REFERENCES urb.municipio(id)
);

-- =========================================================
-- 10) urb.poi_ruta
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.poi_ruta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_poi TEXT NOT NULL,
  id_ruta BIGINT NOT NULL,
  CONSTRAINT fk_poi_ruta_poi
    FOREIGN KEY (id_poi) REFERENCES urb.poi(id),
  CONSTRAINT fk_poi_ruta_ruta
    FOREIGN KEY (id_ruta) REFERENCES urb.ruta(id),
  CONSTRAINT uq_poi_ruta UNIQUE (id_poi, id_ruta)
);

-- =========================================================
-- 11) urb.numero
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.numero (
  numero VARCHAR(20) PRIMARY KEY,
  CONSTRAINT numero_solo_digitos CHECK (numero ~ '^\d+$')
);

-- =========================================================
-- 12) urb.numeros_recargas
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.numeros_recargas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio_recarga TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  fecha_fin_recarga TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  id_numero VARCHAR(20) NOT NULL,
  CONSTRAINT fk_numeros_recargas_numero
    FOREIGN KEY (id_numero) REFERENCES urb.numero(numero)
);

-- =========================================================
-- 15) urb.ruta_base_posicion
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.ruta_base_posicion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta BIGINT NOT NULL,
  latitud DOUBLE PRECISION NOT NULL,
  longitud DOUBLE PRECISION NOT NULL,
  orden INT NOT NULL,
  CONSTRAINT fk_ruta_base_posicion_ruta
    FOREIGN KEY (id_ruta) REFERENCES urb.ruta(id) ON DELETE CASCADE,
  CONSTRAINT uq_ruta_base_posicion_orden UNIQUE (id_ruta, orden)
);
-- =========================================================
-- 18) urb.persona
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.persona (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido_paterno VARCHAR(100) NOT NULL,
  apellido_materno VARCHAR(100),
  telefono VARCHAR(20) NOT NULL,
  id_estado INT NOT NULL,
  CONSTRAINT fk_persona_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id)
);

-- =========================================================
-- 19) urb_sistema.usuario
-- =========================================================
CREATE TABLE IF NOT EXISTS urb_sistema.usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_persona BIGINT NOT NULL,
  nombre_usuario VARCHAR(80) NOT NULL UNIQUE,
  numero VARCHAR(20) NOT NULL,
  contrasena TEXT NOT NULL,
  id_estado INT NOT NULL,
  id_organizacion BIGINT NOT NULL,
  CONSTRAINT fk_usuario_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id),
  CONSTRAINT fk_usuario_organizacion
    FOREIGN KEY (id_organizacion) REFERENCES urb.organizacion(id),
  CONSTRAINT fk_usuario_persona
    FOREIGN KEY (id_persona) REFERENCES urb.persona(id)
);

-- =========================================================
-- 20) urb_sistema.usuario_ciudad
-- =========================================================
CREATE TABLE IF NOT EXISTS urb_sistema.usuario_ciudad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_sistema BIGINT NOT NULL,
  id_ciudad BIGINT NOT NULL,
  CONSTRAINT fk_usuario_ciudad_usuario
    FOREIGN KEY (id_usuario_sistema) REFERENCES urb_sistema.usuario(id),
  CONSTRAINT fk_usuario_ciudad_ciudad
    FOREIGN KEY (id_ciudad) REFERENCES urb.municipio(id)
);

-- =========================================================
-- 21) urb_sistema.usuario_estado
-- =========================================================
CREATE TABLE IF NOT EXISTS urb_sistema.usuario_estado_localidad(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL,
  id_estado_localidad BIGINT NOT NULL,
  CONSTRAINT fk_usuario_estado_usuario
    FOREIGN KEY (id_usuario) REFERENCES urb_sistema.usuario(id),
  CONSTRAINT fk_usuario_estado_estado_localidad
    FOREIGN KEY (id_estado_localidad) REFERENCES urb.estado_localidad(id)
);

-- =========================================================
-- 22) urb.camion
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.camion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_camion VARCHAR(20) NOT NULL,
  placa VARCHAR(30) NOT NULL,
  id_propietario BIGINT NOT NULL,
  id_tipo_camion INT NOT NULL,
  id_organizacion BIGINT NOT NULL,
  id_estado INT NOT NULL,
  CONSTRAINT fk_camion_propietario
    FOREIGN KEY (id_propietario) REFERENCES urb.persona(id),
  CONSTRAINT fk_camion_tipo_camion
    FOREIGN KEY (id_tipo_camion) REFERENCES urb.tipo_camion(id),
  CONSTRAINT fk_camion_organizacion
    FOREIGN KEY (id_organizacion) REFERENCES urb.organizacion(id),
  CONSTRAINT fk_camion_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id)
);

-- =========================================================
-- 23) urb.camion_conductor
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.camion_conductor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_camion BIGINT NOT NULL,
  id_persona BIGINT NOT NULL,
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  dia_inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  dia_fin DATE,
  id_estado INT NOT NULL,
  CONSTRAINT fk_camion_conductor_camion
    FOREIGN KEY (id_camion) REFERENCES urb.camion(id),
  CONSTRAINT fk_camion_conductor_persona
    FOREIGN KEY (id_persona) REFERENCES urb.persona(id),
  CONSTRAINT fk_camion_conductor_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id)
);

-- =========================================================
-- 24) urb.camion_dispositivo (id_device SIN FK)
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.camion_dispositivo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_camion BIGINT NOT NULL,
  id_device BIGINT NOT NULL,
  fecha TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  id_estado INT NOT NULL,
  CONSTRAINT fk_camion_dispositivo_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id),
  CONSTRAINT fk_camion_dispositivo_camion
    FOREIGN KEY (id_camion) REFERENCES urb.camion(id)
);

-- =========================================================
-- 25) urb.vinculo_dispositivo_cel (id_device SIN FK)
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.vinculo_dispositivo_cel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_device BIGINT NOT NULL,
  numero VARCHAR(20) NOT NULL,
  CONSTRAINT fk_vinculo_dispositivo_cel_numero
    FOREIGN KEY (numero) REFERENCES urb.numero(numero)
);

CREATE TABLE IF NOT EXISTS urb.tipo_tarifa (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);
-- =========================================================
-- 26) urb.precio_ruta
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.precio_ruta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta BIGINT NOT NULL,
  precio NUMERIC(10,2) NOT NULL,
  id_tipo_tarifa INT NOT NULL,
  id_estado INT NOT NULL,
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  fecha_modificacion TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT fk_precio_ruta_ruta
    FOREIGN KEY (id_ruta) REFERENCES urb.ruta(id),
  CONSTRAINT fk_precio_ruta_tipo_tarifa
    FOREIGN KEY (id_tipo_tarifa) REFERENCES urb.tipo_tarifa(id),
  CONSTRAINT fk_precio_ruta_estado
    FOREIGN KEY (id_estado) REFERENCES urb.estado(id)
);

-- =========================================================
-- 27) urb.camion_ruta
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.camion_ruta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_camion BIGINT NOT NULL,
  id_ruta BIGINT NOT NULL,
  CONSTRAINT fk_camion_ruta_camion
    FOREIGN KEY (id_camion) REFERENCES urb.camion(id),
  CONSTRAINT fk_camion_ruta_ruta
    FOREIGN KEY (id_ruta) REFERENCES urb.ruta(id),
  CONSTRAINT uq_camion_ruta UNIQUE (id_camion, id_ruta)
);

-- =========================================================
-- FK que quedó pendiente por el orden de creación
-- =========================================================
-- =========================================================
-- 16) urb.ruta_ejecutada
-- (OJO: en tu orden, camion todavía no existe; FK se agrega al final)
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.ruta_ejecutada (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta BIGINT NOT NULL,
  id_camion BIGINT NOT NULL,
  fecha DATE NOT NULL,
  hora_inicio TIME WITHOUT TIME ZONE NOT NULL,
  hora_fin TIME WITHOUT TIME ZONE NOT NULL,
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_ruta_ejecutada_ruta
    FOREIGN KEY (id_ruta) REFERENCES urb.ruta(id),
  CONSTRAINT fk_ruta_ejecutada_camion
    FOREIGN KEY (id_camion) REFERENCES urb.camion(id)
);

-- =========================================================
-- 17) urb.ruta_ejecutada_posicion
-- =========================================================
CREATE TABLE IF NOT EXISTS urb.ruta_ejecutada_posicion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ruta_ejecutada BIGINT NOT NULL,
  latitud DOUBLE PRECISION NOT NULL,
  longitud DOUBLE PRECISION NOT NULL,
  hora TIME WITHOUT TIME ZONE NOT NULL,
  orden INT NOT NULL,
  geom geometry(Point, 4326) NOT NULL,
  CONSTRAINT fk_ruta_ejecutada_posicion_ruta_ejecutada
    FOREIGN KEY (id_ruta_ejecutada) REFERENCES urb.ruta_ejecutada(id) ON DELETE CASCADE,
  CONSTRAINT uq_ruta_ejecutada_posicion_orden UNIQUE (id_ruta_ejecutada, orden)
);
